# Build settings
markdown: redcarpet
highlighter: pygments

# Site settings
title: "Café Linear"
description: > # this means to ignore newlines until "email:"
   F: Coffee ↦ Software

email: douglas@cafelinear.com
#blog logo
logo: "/assets/images/logo-300.png"
# blog cover
cover: "/assets/images/14784796506_e5d956def4_o.jpg"

name: 'Douglas Drumond'
author: 'Douglas Drumond'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://www.cafelinear.com" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  - icon:	cltwitter
    url:	https://twitter.com/douglasdrumond
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: //www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	clgithub
    url:	https://github.com/douglasdrumond
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

  - icon:	clgoogle-plus
    url:	https://google.com/+DouglasDrumond
    desc:	Add me on google+
    share_url:
    share_title:
    share_link:
