baseURL = "https://www.douglasdrumond.tech"
disablePathToLower = "true"
title = "Douglas Drumond Kayama"
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]

# languageCode = "en-us"
defaultContentLanguage = "en"
[languages]
    [languages.en]
        contentDir = "content/en"
        disabled = false
        languageCode = "en-GB"
        languageDirection = "ltr"
        weight = 1
    [languages.pt]
        contentDir = "content/pt"
        disabled = false
        languageCode = "pt-BR"
        languageDirection = "ltr"
        weight = 2

[[params.ananke_socials]]
name = "mastodon"
url = "https://mastodon.acm.org/@douglas"
rel = "me"

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/douglasdrumond"

[[params.ananke_socials]]
name = "github"
url = "https://github.com/douglasdrumond"

[[params.ananke_socials]]
name = "linkedin"
url = "https://www.linkedin.com/in/douglasdrumond"

[[params.ananke_socials]]
name = "instagram"
url = "https://instagram.com/douglasdrumond.tech"

[[params.ananke_socials]]
name = "instagram"
url = "https://instagram.com/_douglasdrumond"
