baseURL = "https://www.cafelinear.com"
disablePathToLower = "true"
languageCode = "en-us"
title = "Café Linear"

theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/douglasdrumond"

[[params.ananke_socials]]
name = "github"
url = "https://github.com/douglasdrumond"

[[params.ananke_socials]]
name = "linkedin"
url = "https://www.linkedin.com/in/douglasdrumond"

[[params.ananke_socials]]
name = "instagram"
url = "https://instagram.com/_douglasdrumond"
