baseURL = "https://www.douglasdrumond.tech"
disablePathToLower = "true"
languageCode = "en-us"
title = "Douglas Drumond Kayama"

theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]

[[params.ananke_socials]]
name = "mastodon"
url = "https://mastodon.acm.org/@douglas"
rel = "me"

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/douglasdrumond"

[[params.ananke_socials]]
name = "github"
url = "https://github.com/douglasdrumond"

[[params.ananke_socials]]
name = "linkedin"
url = "https://www.linkedin.com/in/douglasdrumond"

[[params.ananke_socials]]
name = "instagram"
url = "https://instagram.com/douglasdrumond.tech"

[[params.ananke_socials]]
name = "instagram"
url = "https://instagram.com/_douglasdrumond"
